version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "3306:6603"
    networks:
      -net
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xen0077

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"