version: '3'
services:
#  my-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#      - "3306:6603"
#    networks:
#      -net
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tronico
      MYSQL_ROOT_PASSWORD: password


  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"
